"""SQLAlchemy 모델 (contracts/db-schema.md 그대로). 도메인별 모듈을 전부 export 한다.

alembic/env.py 는 이 패키지를 import 해 Base.metadata 에 전 테이블을 등록한다.
"""

from app.db.models import enums
from app.db.models.enums import (
    ApprovalStatus,
    AuditAction,
    CodePrefix,
    EquipType,
    Inspection,
    LabelFormat,
    LabelTargetType,
    LabelType,
    LotStatus,
    MigrationSource,
    MigrationStatus,
    NotificationChannel,
    NotificationType,
    PrinterPurpose,
    ReceiptStatus,
    Role,
    ScanAction,
    ScanResult,
    ScanTargetType,
    ShipmentStatus,
    SoStatus,
    StationType,
    StepStatus,
    StockSource,
    StockTxnType,
    WoStatus,
)
from app.db.models.master import (
    AppUser,
    CodeSequence,
    Customer,
    CustomerAddress,
    Equipment,
    Item,
    ItemRouting,
    Printer,
    PrintMethod,
    Process,
    RoutingStep,
    Station,
)
from app.db.models.material import InboundLot, MaterialReceipt, Stock, StockTxn, VendorBarcodeMap
from app.db.models.ops import AuditLog, MigrationBatch, MigrationMap, Notification
from app.db.models.order import (
    Design,
    LabelIssue,
    SalesOrder,
    SalesOrderLine,
    StepWork,
    WorkOrder,
    WoRouteStep,
)
from app.db.models.scan import SCAN_EVENT_ID_SEQ, ScanEvent, ScanEventKey
from app.db.models.shipping import PackBox, Shipment, ShipmentBox

__all__ = [
    "SCAN_EVENT_ID_SEQ",
    "AppSetting",
    "AppUser",
    "ApprovalStatus",
    "AuditAction",
    "AuditLog",
    "Carrier",
    "CodePrefix",
    "CodeSequence",
    "Customer",
    "CustomerAddress",
    "Design",
    "EquipType",
    "Equipment",
    "InboundLot",
    "Inspection",
    "Item",
    "ItemGroup",
    "ItemRouting",
    "LabelFormat",
    "LabelIssue",
    "LabelTargetType",
    "LabelTemplate",
    "LabelType",
    "LotStatus",
    "MaterialReceipt",
    "MigrationBatch",
    "MigrationMap",
    "MigrationSource",
    "MigrationStatus",
    "Notification",
    "NotificationChannel",
    "NotificationType",
    "PackBox",
    "PrintMethod",
    "Printer",
    "PrinterPurpose",
    "Process",
    "ReceiptStatus",
    "Role",
    "RoutingStep",
    "SalesOrder",
    "SalesOrderLine",
    "ScanAction",
    "ScanEvent",
    "ScanEventKey",
    "ScanResult",
    "ScanTargetType",
    "Shipment",
    "ShipmentBox",
    "ShipmentStatus",
    "SoStatus",
    "Station",
    "StationType",
    "StepStatus",
    "StepWork",
    "Stock",
    "StockSource",
    "StockTxn",
    "StockTxnType",
    "VendorBarcodeMap",
    "WoRouteStep",
    "WoStatus",
    "WorkOrder",
    "enums",
]
